### ISSUE TITLE
Error "Not enough lines: 1. Getting more"

### ISSUE THREAD

**Issue by jes1417** [eseglem/hass-wattbox#19]
## Version of the custom_component 

```v0.9.0b5```

## Configuration

```wattbox:
  - host: 10.30.46.119
    port: 22
    name: Network Wattbox
    username: myusername
    password: mypassword
    scan_interval: 00:00:30
    resources:
      - cloud_status
      - auto_reboot
      - mute
      - safe_voltage_status
      - current_value
      - power_value
      - voltage_value
```

Add your logs here.

```This error originated from a custom integration.

Logger: pywattbox.async_driver
Source: custom_components/wattbox/__init__.py:143
Integration: WattBox (documentation, issues)
First occurred: 4:04:02 PM (19 occurrences)
Last logged: 4:26:32 PM

Not enough lines: 1. Getting more
```

## Describe the bug

annoying repeating error in logs

## Debug log

only thing I see when enabling debug
```
2023-12-12 16:36:32.925 DEBUG (MainThread) [custom_components.wattbox] Updated: WattBox (10.30.46.119): WB-800-IPVM-6 - <pywattbox.ip_wattbox.IpWattBox object at 0x7f6d938e6050>
```

Add your logs here.

**Comment by eseglem** [comment]
Is it actually connecting and pulling data or not getting anything? The debug logs tend to be repetitive and should be seeing some lines every time it pulls data based on your scan interval. 

That line alone isn't necessarily an error, it's reading lines from the server response and sometimes needs to get more to find the end of the data.

It looks like it's connecting some amount, since it's got a model (WB-800-IPVM-6). Is there an issue other than the logs?

If there is an issue, there should be a lot more logs than that. May need to turn on debug for scrapli as well. Otherwise turning off debug for pywattbox should get rid of those statements. 

I'd also remove the resources section from your config as well. It's not necessary, unless you actually don't want all the data.

**Comment by jes1417** [comment]
This seems to have went away when I updated the wattbox to the october 23 firmware

**Comment by jes1417** [comment]
they ended up coming back.

**Comment by eseglem** [comment]
Realized this is probably more of a `pywattbox` issue, the logs are coming from there. It was set as error there, while figuring things out. Looks like it should probably be more of a debug statement, since it is able to handle that situation now. Can tweak that next time there is a release of it. 

In the meantime should be able to suppress them with the logging config.

```yaml
logger:
  logs:
    pywattbox: critical
```
